import type { Metadata } from "next";
import localFont from "next/font/local";
import ApolloContainer from "@/containers/ApolloContainer";
import "./globals.css";
import Link from "next/link";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

const navigations = [
  {
    href: '/newest',
    label: 'new'
  },
  {
    href: '/ask',
    label: 'ask'
  },
  {
    href: '/show',
    label: 'show'
  },
  {
    href: '/jobs',
    label: 'jobs'
  },
]

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <ApolloContainer>
          <div className="container mx-auto">
            <header className="bg-orange-600">
              <nav className="space-x-2">
                <Link href='/' className="font-semibold">Hacker News</Link>
                {navigations.map(({ href, label }) => (
                  <Link key={href} href={href}>{label}</Link>
                ))}
              </nav>
            </header>
            <main>
              {children}
            </main>
          </div>
        </ApolloContainer>
      </body>
    </html>
  );
}
