import type { Metadata } from "next";
import localFont from "next/font/local";
import ApolloContainer from "@/containers/ApolloContainer";
import "./globals.css";
import Link from "next/link";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <ApolloContainer>
          <div className="container mx-auto">
            <header className="bg-orange-600">
              <nav className="space-x-2">
                <Link href='/' className="font-semibold">Hacker News</Link>
                <Link href='/new'>new</Link>
                <Link href='/ask'>ask</Link>
              </nav>
            </header>
            <main>
              {children}
            </main>
          </div>
        </ApolloContainer>
      </body>
    </html>
  );
}
